export const TEA_GREEN = "#C5E6A6"
export const MANA_TEA = "#9899A6"
export const COTTON_BOLL = "#E7F0FF"
export const BLACK = "#000000"
export const SOFTENED_GREEN = "#B9BEA5"
export const WHITE = "#ffffff"