export const TEA_GREEN = "#C5E6A6"
export const QUICK_SILVER = "#A7AAA4"
export const MANA_TEA = "#9899A6"
export const COTTON_BOLL = "#E7F0FF"
export const BLACK = "#000000"
export const WHITE = "#ffffff"